### ISSUE TITLE
Issue in isFutureOnly

### ISSUE THREAD

**Issue by nakkeeran** [mugifly/jquery-simple-datetimepicker#105]
Hi,

When the user selects a tomorrow's date and morning 1:00 AM and when the user select today's date the time still selects the 1:00 AM which is not future anymore.

Thanks,
Nike

**Comment by mugifly** [comment]
This issue was fixed for now. Thank you for report :)
http://jq-simple-dtpicker-gh-master.herokuapp.com/jquery.simple-dtpicker.html
