### ISSUE TITLE
Hungarian translation

### ISSUE THREAD

**Issue by greenformatics-peter** [mugifly/jquery-simple-datetimepicker#126]
hu: {
			days: ['Va', 'Hé', 'Ke', 'Sze', 'Cs', 'Pé', 'Szo'],
			months: [ "Jan", "Feb", "Már", "Ápr", "Máj", "Jún", "Júl", "Aug", "Szep", "Okt", "Nov", "Dec" ],
			sep: '-',
			format: 'YYYY-MM-DD hh:mm:00',
			prevMonth: 'Előző hónap',
			nextMonth: 'Következő hónap',
			today: 'Ma'
		}

**Comment by mugifly** [comment]
Thanks :)
