### ISSUE TITLE
Not possible to set minDate or maxDate

### ISSUE THREAD

**Issue by funewik** [mugifly/jquery-simple-datetimepicker#131]
Hello,

With the following fiddle : http://jsfiddle.net/3SNEq/2/, the datetime picker is well set for the minDate or MaxDate when setting up these datas directly in the appendDtpicker() method.

But by using handleDtpicker() method, i have this error :
Uncaught TypeError: Cannot read property 'apply' of undefined

Is there any solution to set a min or a max date ?

Thanks

**Comment by royzrj** [comment]
This issue is fixed on master branch, and this issue is the same as #140 and #144
