### ISSUE TITLE
Picker gets closed when clicking in appended input box

### ISSUE THREAD

**Issue by chrigu83** [mugifly/jquery-simple-datetimepicker#135]
"appendDtpicker()" binds the click event of the appended input box. When the event is fired, the eventhandler checks the activePickerId, based on this id the picker will be opened or closed. There is another eventHandler which is binded on the "hover" of the picker which sets and removes the activePickerId.
The Problem is, that when the mouse leaves the picker, the activePickerId will be set to -1.

to reproduce this issue:
1) click in the appended input box --> picker gets opened
2) navigate the mouse over the picker --> activePickerId gets set
3) navigate the mouse to an other window and click to set the focus --> activePickerId gets set to -1
4) click in the appended input box --> picker gets closed.

The problem could be fixed by adding the same hover event handler also to the input box.

Regards

**Comment by royzrj** [comment]
Duplicate #82
