### ISSUE TITLE
Unable to set Date Range (from date - to date)

### ISSUE THREAD

**Issue by naga2raja** [mugifly/jquery-simple-datetimepicker#144]
When the user select the start date then in the End date box, I want to disable the dates before the start date. 

Is the functionality is already been done, because In the example I saw date range but that was also not working.

**Comment by royzrj** [comment]
@naga2raja the above merged pull request contains code that does what you need

**Comment by royzrj** [comment]
@mugifly I think this issue can be closed, what do you think?

**Comment by naga2raja** [comment]
@royzrj The issue doesn't occur in the master branch ..  Let's close this issue.
